// <auto-generated />
using System;
using KOP.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KOP.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250514114732_MakeDateFieldsNullableInUserEntity")]
    partial class MakeDateFieldsNullableInUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KOP.DAL.Entities.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentTypeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("SystemStatus")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId");

                    b.HasIndex("AssessmentTypeId", "GradeId")
                        .IsUnique();

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentInterpretation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Competence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HtmlClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentTypeId");

                    b.ToTable("AssessmentInterpretations");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxAssessmentMatrixResultValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinAssessmentMatrixResultValue")
                        .HasColumnType("integer");

                    b.Property<int>("SystemType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AssessmentMatrices");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentMatrixElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<string>("HtmlClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MatrixId")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId");

                    b.ToTable("AssessmentMatrixElements");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRangeValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinRangeValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AssessmentRanges");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<int>("JudgeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ResultDate")
                        .HasColumnType("date");

                    b.Property<int>("SystemStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("JudgeId");

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentResultValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentMatrixRow")
                        .HasColumnType("integer");

                    b.Property<int>("AssessmentResultId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentResultId");

                    b.ToTable("AssessmentResultValues");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentMatrixId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SystemAssessmentType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentMatrixId");

                    b.ToTable("AssessmentTypes");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorporateCompetenciesConclusion")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GradeStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorporateCompetenciesFinalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKpisFinalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManagmentCompetenciesFinalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMarksFinalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProjectsFinalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQualificationFinalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStrategicTasksFinalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValueJudgmentFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("KPIsConclusion")
                        .HasColumnType("text");

                    b.Property<string>("ManagmentCompetenciesConclusion")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<double>("Qn2")
                        .HasColumnType("double precision");

                    b.Property<string>("QualificationConclusion")
                        .HasColumnType("text");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StrategicTasksConclusion")
                        .HasColumnType("text");

                    b.Property<int>("SystemStatus")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ValueJudgmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("ValueJudgmentId")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("KOP.DAL.Entities.HigherEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.Property<string>("QualificationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.ToTable("HigherEducations");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Kpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompletionPercentage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Kpis");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<int>("MarkTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("PercentageValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("MarkTypeId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("KOP.DAL.Entities.MarkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MarkTypes");
                });

            modelBuilder.Entity("KOP.DAL.Entities.PreviousJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.ToTable("PreviousJobs");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageKpi")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SP")
                        .HasColumnType("double precision");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double precision");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentExperienceMonths")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentJobPositionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CurrentJobStartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CurrentStatusDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<string>("EmploymentContarctTerminations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<string>("QualificationResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("KOP.DAL.Entities.StrategicTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FactDate")
                        .HasColumnType("date");

                    b.Property<string>("FactResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date");

                    b.Property<string>("PlanResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("StrategicTasks");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Subdivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NestingLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Subdivisions");
                });

            modelBuilder.Entity("KOP.DAL.Entities.TrainingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Competence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("TrainingEvents");
                });

            modelBuilder.Entity("KOP.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ContractStartDate")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentFromFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GradeGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentSubdivisionId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StructureRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubdivisionFromFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("SystemRoles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("ParentSubdivisionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KOP.DAL.Entities.ValueJudgment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BehaviorToCorrect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("RecommendationsForDevelopment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ValueJudgments");
                });

            modelBuilder.Entity("SubdivisionUser", b =>
                {
                    b.Property<int>("SubordinateSubdivisionsId")
                        .HasColumnType("integer");

                    b.Property<int>("SupervisingUsersId")
                        .HasColumnType("integer");

                    b.HasKey("SubordinateSubdivisionsId", "SupervisingUsersId");

                    b.HasIndex("SupervisingUsersId");

                    b.ToTable("SubdivisionUser");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Assessment", b =>
                {
                    b.HasOne("KOP.DAL.Entities.AssessmentType", "AssessmentType")
                        .WithMany("Assessments")
                        .HasForeignKey("AssessmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOP.DAL.Entities.Grade", "Grade")
                        .WithMany("Assessments")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOP.DAL.Entities.User", "User")
                        .WithMany("Assessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentType");

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentInterpretation", b =>
                {
                    b.HasOne("KOP.DAL.Entities.AssessmentType", "AssessmentType")
                        .WithMany("AssessmentInterpretations")
                        .HasForeignKey("AssessmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentType");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentMatrixElement", b =>
                {
                    b.HasOne("KOP.DAL.Entities.AssessmentMatrix", "Matrix")
                        .WithMany("Elements")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentResult", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOP.DAL.Entities.User", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Judge");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentResultValue", b =>
                {
                    b.HasOne("KOP.DAL.Entities.AssessmentResult", "AssessmentResult")
                        .WithMany("AssessmentResultValues")
                        .HasForeignKey("AssessmentResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentResult");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentType", b =>
                {
                    b.HasOne("KOP.DAL.Entities.AssessmentMatrix", "AssessmentMatrix")
                        .WithMany("AssessmentTypes")
                        .HasForeignKey("AssessmentMatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentMatrix");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Grade", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Qualification", "Qualification")
                        .WithOne("Grade")
                        .HasForeignKey("KOP.DAL.Entities.Grade", "QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOP.DAL.Entities.User", "User")
                        .WithMany("Grades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOP.DAL.Entities.ValueJudgment", "ValueJudgment")
                        .WithOne("Grade")
                        .HasForeignKey("KOP.DAL.Entities.Grade", "ValueJudgmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("User");

                    b.Navigation("ValueJudgment");
                });

            modelBuilder.Entity("KOP.DAL.Entities.HigherEducation", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Qualification", "Qualification")
                        .WithMany("HigherEducations")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Kpi", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Grade", null)
                        .WithMany("Kpis")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KOP.DAL.Entities.Mark", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Grade", "Grade")
                        .WithMany("Marks")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOP.DAL.Entities.MarkType", "MarkType")
                        .WithMany("Marks")
                        .HasForeignKey("MarkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("MarkType");
                });

            modelBuilder.Entity("KOP.DAL.Entities.PreviousJob", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Qualification", "Qualification")
                        .WithMany("PreviousJobs")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Project", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Grade", "Grade")
                        .WithMany("Projects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("KOP.DAL.Entities.StrategicTask", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Grade", "Grade")
                        .WithMany("StrategicTasks")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Subdivision", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Subdivision", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("KOP.DAL.Entities.TrainingEvent", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Grade", "Grade")
                        .WithMany("TrainingEvents")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("KOP.DAL.Entities.User", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Subdivision", "ParentSubdivision")
                        .WithMany("Users")
                        .HasForeignKey("ParentSubdivisionId");

                    b.Navigation("ParentSubdivision");
                });

            modelBuilder.Entity("SubdivisionUser", b =>
                {
                    b.HasOne("KOP.DAL.Entities.Subdivision", null)
                        .WithMany()
                        .HasForeignKey("SubordinateSubdivisionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOP.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SupervisingUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KOP.DAL.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentResults");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentMatrix", b =>
                {
                    b.Navigation("AssessmentTypes");

                    b.Navigation("Elements");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentResult", b =>
                {
                    b.Navigation("AssessmentResultValues");
                });

            modelBuilder.Entity("KOP.DAL.Entities.AssessmentType", b =>
                {
                    b.Navigation("AssessmentInterpretations");

                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Grade", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Kpis");

                    b.Navigation("Marks");

                    b.Navigation("Projects");

                    b.Navigation("StrategicTasks");

                    b.Navigation("TrainingEvents");
                });

            modelBuilder.Entity("KOP.DAL.Entities.MarkType", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Qualification", b =>
                {
                    b.Navigation("Grade")
                        .IsRequired();

                    b.Navigation("HigherEducations");

                    b.Navigation("PreviousJobs");
                });

            modelBuilder.Entity("KOP.DAL.Entities.Subdivision", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KOP.DAL.Entities.User", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("KOP.DAL.Entities.ValueJudgment", b =>
                {
                    b.Navigation("Grade")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
